# Netlify Configuration for Docs App
# Documentation: https://docs.netlify.com/build/configure-builds/file-based-configuration/

[build]
  # Build command - only build docs and its dependencies, skip other apps
  command = "cd apps/docs && npm run build"

  # Publish directory - handled by Next.js plugin
  publish = ".next"

  # Package directory - where this app's source files are located
  # Set this in Netlify UI: apps/docs

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "11.6.2"

# Ignore builds - only build when docs app or shared packages change
[build.ignore]
  command = '''
    if [ "$CACHED_COMMIT_REF" = "" ]; then
      echo "First build - building"
      exit 1
    fi

    # Check if docs app or shared packages changed
    git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/docs packages/typescript-config packages/eslint-config package.json turbo.json
  '''

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Essential Next.js Runtime Plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
